"""Convert models to SQLAlchemy 2.0 style

Revision ID: f148f27d4e1c
Revises: dc832a62202d
Create Date: 2025-04-01 13:14:02.718272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f148f27d4e1c'
down_revision: Union[str, None] = 'dc832a62202d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_bases_id', table_name='knowledge_bases')
    op.drop_index('ix_permissions_id', table_name='permissions')
    op.drop_index('ix_tenants_id', table_name='tenants')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_tenant_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'is_tenant_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index('ix_tenants_id', 'tenants', ['id'], unique=False)
    op.create_index('ix_permissions_id', 'permissions', ['id'], unique=False)
    op.create_index('ix_knowledge_bases_id', 'knowledge_bases', ['id'], unique=False)
    # ### end Alembic commands ###
