name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      env:
        UV_VERSION: 0.2.7

    - name: Add uv to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create and activate virtualenv
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv sync --dev

    - name: Run core tests
      working-directory: ./packages/ragnarok_core
      run: |
        source ../../.venv/bin/activate
        uv pip install -e .
        pytest -v

    - name: Run server tests
      working-directory: ./packages/ragnarok_server
      run: |
        source ../../.venv/bin/activate
        uv pip install -e .
        pytest -v

    - name: Run toolkit tests
      working-directory: ./packages/ragnarok_toolkit
      run: ~/.cargo/bin/uv pip install -e . && pytest -v
